# Site settings
title: Portfolio Eevee Creations
email: karremanseefje@outlook.com
description: > 
  This portfolio  is supposed to simply showcase the activities to do within my education and spare time
baseurl: "" 
url: "" 
github_username: Eevee Creations

markdown: kramdown

collections:
  portfolio:
    output: true