# Site settings
title: PortFolio Eevee Creations
email: karremanseefje@outlook.com
description: > 
  This portfolio  is suposed to simply showcase the activities to do s within my education and spare time
baseurl: "" 
url: "" 
github_username: Eevee Creations

markdown: kramdown
